sudo: required
services:
  - docker

before_install: 
  - docker build -t annantguptacs15/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true annantguptacs15/react-test npm test

after_success: 
  - docker build -t annantguptacs15/multi-client ./client
  - docker build -t annantguptacs15/multi-nginx ./nginx
  - docker build -t annantguptacs15/multi-server ./server
  - docker build -t annantguptacs15/multi-worker ./worker

# login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # push the images to docker hub
  - docker push annantguptacs15/multi-client
  - docker push annantguptacs15/multi-nginx
  - docker push annantguptacs15/multi-server
  - docker push annantguptacs15/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-805746249177
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"